[module]

[module.hugoVersion]
min = "0.74.0"
extended = false

[[module.mounts]]
source = "page/index.md"
target = "content/hugo-icons-listing.md"

[[module.mounts]]
source = "page/template.html"
target = "layouts/_default/hugo-icons-listing.html"

[[module.mounts]]
source = "partials"
target = "layouts/partials/hugo-icons"

[[module.imports]]
path = "github.com/twbs/icons"

[[module.imports.mounts]]
source = "icons"
target = "assets/hugo-icons/icons"